### ISSUE TITLE
Visualize overall partner report: Progress report section 2

### ISSUE THREAD

**Issue by ninetteadhikari** [toladata-ce/TolaReports#4]
### Story 
User wants to see overall activity progress of all the partners. 

1. Data is to be filtered by Year, corresponding Month, and Activity type
2. Data tables or charts to be generated:
![image](https://user-images.githubusercontent.com/13760198/42779399-2c746852-88f5-11e8-849a-298b24a054f9.png)

![image](https://user-images.githubusercontent.com/13760198/42779291-cf70387a-88f4-11e8-8781-1a0eac11ccd2.png)

Data source:
Survey data from Track. Standard format: https://docs.google.com/spreadsheets/d/165dNChI_f0oQT3xf83fSvL-QEPLmeSZ_hLcU6D3DBZs/edit#gid=0

### Acceptance criteria
GIVEN 
User has added survey data in Track
User has shared the survey data to TD team to be visualized

WHEN 
Users access the report link provided

THEN
• User chooses Year filter
• User is given the option to choose corresponding Month filter
• User chooses Activity type
• User can see the filtered view of the data points

When no filter is chosen total value for all year, month, and activity types are displayed

**Comment by prabhant** [comment]
Resolved with commit latest commit
